name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.local/share/pnpm/store/v3
          key: cache-pnpm-${{ hashFiles('./pnpn-lock.yaml') }}
          restore-keys: cache-pnpm-

      - name: Install pnpm
        run: corepack enable; corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm i

      - name: Build project
        run: npm run build

      - name: Get project data
        run: echo "DATA_JSON=$(jq -c . < source/data.json)" >> $GITHUB_ENV

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: '${{ fromJson(env.DATA_JSON).SERVER_ROOT }}'
          branch: gh-pages
          single-commit: true
